name: Build and deploy Vite React static site to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install Dependencies
        run: |
          npm install
          npm ci

      - name: Build
        run: |
          npm run build || true
          mkdir -p dist  # Tạo thư mục dist nếu chưa tồn tại
          cp public/Web.config dist/Web.config || true  # Thêm || true để bỏ qua lỗi nếu file không tồn tại

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: vite-react-build
          path: dist # Thay đổi từ 'build' sang 'dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vite-react-build
    
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'domstorefe'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07CB3E33FD534698971B57149F1DB5CB }}