name: Build and Deploy Vite React to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Prepare Web Config
      run: |
        cp web.config dist/web.config

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vite-react-app
        path: dist
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: vite-react-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'domstorefe'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_07CB3E33FD534698971B57149F1DB5CB }}